export function consoleLogo() {
  return console.log(
    `
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMWX%ckxxOXW%cMMMMMMMMWNNWWMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMW0%co:;:d0XM%cMMMMWXOOKWMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMW0%cl;;;,:lO%cWMMWKd%cc;;:x%cNMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMN%cd;;;;,:oO%cMMMXo%c,''''cK%cMMMMMMMMMMM
        MMMMMMMMMMMMMMMMM%col;;;;;oo%cXMMMO:%c,''''oN%cMMMMMMMMMMM
        MMMMMMMMMMWNNXNX%cXx:;;;;;d%c0KXXKo%c,,''',d%cKXXXXXXXXXNW
        MMMMMMMMMM%cXxllccc:;;;;;;::::::;,,'''',;;;;;;;;;;%c:d
        MMMMMMMMMMW%c0l:;;;;;;;;;,,,,,,,,,,''''''''''......%c'
        MMMMMMMMMMMW%ckc;;;;;;;;;,,,,,,,,,,,''''''''......%c,l
        MMMMMMMMMMMMN0O%cxc;;;;;c%cxkkkkkkkkkkkkkkkkkkkkxxxkKN
        MMMMMMMMMMMMMM%cW0c:::;:%cxNMMMMXOkkkkk0WMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWNK0000KXWMMMWk%c;,,,',dN%cMMMMMMMMMMMMM
        MWKOkkkxkkxxxxxxxxxxxxxxxxxd%cc,,,'',c%cdddx0WMMMMMMMM
        Nkl%c::::::::;;;;;;;;;;,,,,,,,,,,,,''''',o%cKMMMMMMMMM
        X%cd::::::::;;;;;;;;;,;;,,,,,,,,,,,,''';d%cXMMMMMMMMMM
        WK%ckdoooooooool:;;;;;;cllllc;,,,,,;:cl%ckNMMMMMMMMMMM
        MMWWWWWWWWWWN%c0l;;;;;l%c0NWNN%ck:,,,,,l%cKNWWMMMMMMMMMMMM
        MMMMMMMMMMMM%cWk:;;;;;%cxNMMN%cXx;,,,,;%cxWMMMMMMMMMMMMMMM
        MMMMMMMMMMMM%cNx;;;;;%cl0MMMK%ckl,,,,,c%c0MMMMMMMMMMMMMMMM
        MMMMMMMMMMMMW%cKdllo%cxKWMMMXk%cl,,,,c%ckNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWNNWWMMMMMWWXkxxOXWMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      `,
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#222;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;",
    "color:#6656ff;",
    "color:#fff;"
  );
}
