name: ZReview Deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access Secrets
        run: |
          echo "CRYPTOJS_SECRET_KEY=${{ secrets.REACT_APP_CRYPTOJS_SECRET_KEY }}" >> .env
          echo "KAKAOMAP_KEY=${{ secrets.REACT_APP_KAKAOMAP_KEY }}" >> .env
        env:
          CREDENTIALS: ${{ secrets.REACT_APP_CRYPTOJS_SECRET_KEY }}
            ${{ secrets.REACT_APP_KAKAOMAP_KEY }}
